base_frame_id: base_link
beam_skip_distance: 0.5
beam_skip_threshold: 0.3
do_beamskip: false
first_map_only: false
#initial_pose_a: 0.0
#initial_pose_x: 0.0
#initial_pose_y: 0.0
global_frame_id: map
gui_publish_rate: -1.0
kld_err: 0.01
kld_z: 0.99
laser_lambda_short: 0.1
laser_likelihood_max_dist: 4.0
laser_max_beams: 300
laser_max_range: -1.0
laser_min_range: -1.0
laser_model_type: likelihood_field
laser_sigma_hit: 0.1
laser_z_hit: 0.85
laser_z_max: 0.05
laser_z_rand: 0.15
laser_z_short: 0.1
max_particles: 2000
min_particles: 300
odom_alpha1: 0.5
odom_alpha2: 0.15
odom_alpha3: 0.5
odom_alpha4: 0.15
odom_alpha5: 0.2
odom_frame_id: odom
odom_model_type: omni-corrected
recovery_alpha_fast: 0.1
recovery_alpha_slow: 0.001
resample_interval: 1
restore_defaults: false
save_pose_rate: 0.5
selective_resampling: true
transform_tolerance: 0.1
update_min_a: 0.01
update_min_d: 0.1
use_map_topic: false